#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#index:
#    path: /
#    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#    defaults:
#        template: 'index.html.twig'
#login:
#    path: /login
#    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#        template: 'login.html.twig'
#register:
#    defaults:
#        template: 'register.html.twig'
logout:
    path: /logout